version: "3.9"

services:
    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            dockerfile: ./Dockerfile
            target: client
            args:
              CLIENT_PORT: ${CLIENT_PORT}
        ports:
            - "${CLIENT_PORT}:80"
        environment:
          CLIENT_PORT: ${CLIENT_PORT}
          SERVER_PORT: ${SERVER_PORT}

    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: ./Dockerfile
            target: server
            args:
              SERVER_PORT: ${SERVER_PORT}
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        depends_on:
          - postgres
        environment:
          SERVER_PORT: ${SERVER_PORT}
          NODE_ENV: production
        depends_on:
          - postgres

    postgres:
      image: postgres:14-alpine
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data
