export { delay } from './delay'
export { clamp } from './clamp'
export { linearInterpolation } from './linearInterpolation'
export { loadImage } from './loadImage'
export { randomInRange } from './randomInRange'
export { roundDecimals } from './roundDecimals'
export { withChance } from './chance'
export { Point } from './point'
export type { PointLike } from './point'
