export { delay } from './delay'
export { clamp } from './clamp'
export { lerp } from './lerp'
export { loadImage } from './loadImage'
export { randomInRange } from './randomInRange'
export { roundDecimals } from './roundDecimals'
export { Point } from './point'
export type { PointLike } from './point'
