name: Docker Image CI

on:
  workflow_dispatch:
    branches:
      - test-deploy
      - final-review

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Yandex Cloud CR Login
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SERVICE_ACCOUNT_JSON_CREDENTIALS }}

    - name: Build the Docker image
      env:
        CR_ID: ${{ secrets.YC_ID_CR }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build --target=client -t cr.yandex/$CR_ID/prakticum-client:$IMAGE_TAG .
        docker push cr.yandex/$CR_ID/prakticum-client:$IMAGE_TAG
        docker build --target=server -t cr.yandex/$CR_ID/prakticum-server:$IMAGE_TAG .
        docker push cr.yandex/$CR_ID/prakticum-server:$IMAGE_TAG
